<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
